name: Build self-contained binaries
on: [push, workflow_dispatch]

env:
  PROJECT_PATH: HelloWorld/HelloWorld.csproj
  DOTNET_NOLOGO: true # Suppress the first-time .NET welcome message, etc.

jobs:
  publish:
    name: ${{ matrix.runtime-id }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # Until cross-platform native AOT compilation is supported, let's do the native AOT builds on runners that match the target runtime.
        include:
          - runtime-id: linux-x64
          - runtime-id: linux-arm64

          - runtime-id: win-x64
            artifact-extension: .exe
          - runtime-id: win-arm64
            artifact-extension: .exe

          - runtime-id: osx-x64
          - runtime-id: osx-arm64

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Build and publish the native binary app
        run: dotnet publish ${{ env.PROJECT_PATH }} -p:PublishAot=false -p:PublishTrimmed=true --self-contained -r ${{ matrix.runtime-id }} -o ./out/${{ matrix.runtime-id }}

      - uses: actions/upload-artifact@v4
        with:
          name: HelloWorld-${{ matrix.runtime-id }}
          path: ${{ github.workspace }}/out/${{ matrix.runtime-id }}/HelloWorld${{ matrix.artifact-extension || '' }}
          retention-days: 3

#  release:
#    needs: publish
#    runs-on: ubuntu-latest
#    steps:
#      
#      - uses: softprops/action-gh-release@v2
#        with:
#          files: |
#            out/*