name: Build
on: [push, workflow_dispatch]

jobs:
  publish:
    name: ${{ matrix.os }}-${{ github.workflow }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - if: matrix.os == 'ubuntu-latest'
        run: |
          dotnet publish -r linux-x64 -c Release -o out/x64
          dotnet publish -r linux-arm64 -c Release -o out/arm64

      - if: matrix.os == 'macos-latest'
        run: |
          dotnet publish -r osx-x64 -c Release -o out/x64
          dotnet publish -r osx-arm64 -c Release -o out/arm64

      - if: matrix.os == 'windows-latest'
        run: |
          dotnet publish -r win-x64 -c Release -o out/x64
          dotnet publish -r win-arm64 -c Release -o out/arm64
  
  release:
    needs: publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: out
      
      - uses: softprops/action-gh-release@v2
        with:
          files: |
            out/x64/*
            out/arm64/*