name: Build
on: [push, workflow_dispatch]

jobs:
  publish:
    name: ${{ matrix.runtime-id }}-${{ github.workflow }}-${{ matrix.os }}]
    env:
      PROJECT_PATH: HelloWorld/HelloWorld.csproj
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # Until cross-platform publishing is supported, let's do the native AOT builds on a platform-specific basis.
        include:
          - os: ubuntu-22.04
            runtime-id: linux-x64
          - os: ubuntu-22.04-arm
            runtime-id: linux-arm64
            
          - os: windows-latest
            runtime-id: win-x64
          - os: windows-11-arm
            runtime-id: win-arm64
            
          - os: macos-latest # macOS runners are arm64, but they can cross-compile for x64, so let's use it twice (once per `runtime-id`)
            runtime-id: osx-x64
          - os: macos-latest
            runtime-id: osx-arm64

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - run: dotnet publish $PROJECT_PATH --self-contained -r ${{ matrix.runtime-id }} -o ../out/${{ matrix.runtime-id }}
        env:
          DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
        
      - uses: actions/upload-artifact@v4
        with:
          name: hello
          path: ./out/${{ matrix.runtime-id }}/*
          retention-days: 3
  
  release:
    needs: publish
    runs-on: ubuntu-latest
    steps:
      
      - uses: softprops/action-gh-release@v2
        with:
          files: |
            out/x64/*
            out/arm64/*