name: Build
on: [push, workflow_dispatch]

jobs:
  publish:
    name: ${{ matrix.os }}-${{ github.workflow }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [
          ubuntu-22.04, ubuntu-22.04-arm,
          windows-latest, windows-11-arm,
          macos-latest
        ]

    steps:
      - run: |
          echo "RUNNER_OS: $env:RUNNER_OS"
          echo "RUNNER_ARCH: $env:RUNNER_ARCH"
        
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
          
#      - env:
#          OS: ${{ matrix.os == 'windows-latest' && 'win' || (matrix.os == 'macos-latest' && 'osx' || 'linux') }}
#          OS: ${{ $env:RUNNER_OS == 'win32' && 'win' || (os.platform() == 'darwin' && 'osx' || 'linux') }}
      - run: |
          dotnet publish HelloWorld/HelloWorld.csproj -r ${{ env.OS }}-${{ os.arch() }} -c Release -o out/x64

      # The default mac runner is arm64, but it can cross=compile for x64 so let's do it as an extra step
#      - if: os.platform() == 'darwin'
#        run: dotnet publish HelloWorld/HelloWorld.csproj -r osx-x64 -c Release -o out/x64
  
  release:
    needs: publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/upload-artifact@v4
        with:
          name: out

      - uses: actions/download-artifact@v4
        with:
          name: out
      
      - uses: softprops/action-gh-release@v2
        with:
          files: |
            out/x64/*
            out/arm64/*