name: Build
on: [push, workflow_dispatch]

env:
  PROJECT_PATH: HelloWorld/HelloWorld.csproj
  DOTNET_NOLOGO: true # Suppress the first-time .NET welcome message, etc.

jobs:
  publish:
    name: ${{ env.RID }}
    env:
      RID: ${{ matrix.os }}-${{ matrix.arch }}
      RUNNER: ${{
        env.RID == 'win-x64' && 'windows-latest' || \
        env.RID == 'win-arm64' && 'windows-11-arm' || \
        env.RID == 'osx-x64' && 'macos-latest' || \
        env.RID == 'osx-arm64' && 'macos-latest' || \
        env.RID == 'linux-x64' && 'ubuntu-22.04' || \
        env.RID == 'linux-arm64' && 'ubuntu-22.04-arm'
      }}
    runs-on: ${{ env.RUNNER }}
    strategy:
      fail-fast: false
      matrix:
        # Until cross-platform native AOT compilation is supported, let's do the native AOT builds on runners that match the target runtime.
        os: [win, osx, linux]
        arch: [x64, arm64]
#        include:
#          - os: ubuntu-22.04
#            runtime-id: linux-x64
#          - os: ubuntu-22.04-arm
#            runtime-id: linux-arm64
#            
#          - os: windows-latest
#            runtime-id: win-x64
#          - os: windows-11-arm
#            runtime-id: win-arm64
#            
#          - os: macos-latest # macOS runners are arm64, but they can cross-compile for x64, so let's use it twice (once per `runtime-id`)
#            runtime-id: osx-x64
#          - os: macos-latest
#            runtime-id: osx-arm64

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Build and publish the native binary app
        run: dotnet publish ${{ env.PROJECT_PATH }} --self-contained -r ${{ env.RID }} -o ./out/${{ env.RID }}
        
      - uses: actions/upload-artifact@v4
        with:
          name: HelloWorld-${{ env.RID }}
          path: ${{ github.workspace }}/out/${{ env.RID }}/*
          retention-days: 3
  
  release:
    needs: publish
    runs-on: ubuntu-latest
    steps:
      
      - uses: softprops/action-gh-release@v2
        with:
          files: |
            out/*